import { useState } from "react";
import type { MouseEventHandler } from "react";
import Head from "next/head";
import { LazyImage } from "../src/components/LazyImage";
import { v4 as uuid } from "uuid";
import PageContent from "@/src/components/PageContent";
import ThemeComponent from "@/src/components/ThemeComponent";

const randomNumber = (): number => {
  let valueFinal: number = 123;

  const resultRandom: number = Math.floor(Math.random() * valueFinal);
  return resultRandom;
};

export default function Home() {
  // const [images, setImages] = useState<string[]>([]); other
  const [images, setImages] = useState<Array<IFoxImageItems>>([]);

  const addNewFox: MouseEventHandler<HTMLButtonElement> = (event) => {
    const newImageItem: IFoxImageItems = {
      id: uuid(),
      url: `https://randomfox.ca/images/${randomNumber()}.jpg`,
    };

    setImages([...images, newImageItem]);
  };

  return (
    <>
      <Head>
        <title>React With Typescript</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🦊</text></svg>"
        />
      </Head>
      <main className="container mx-auto p-4 flex flex-col items-center dark:bg-slate-800">
        <ThemeComponent />
        <PageContent />
        <button onClick={addNewFox}>Add new Fox</button>
        <div className="flex flex-wrap justify-center">
          {images.map(({ id, url }) => (
            <div key={id} className="p-4">
              <LazyImage
                src={url}
                width={320}
                height={320}
                className={"rounded bg-gray-300 object-cover"}
              />
            </div>
          ))}
        </div>
      </main>
    </>
  );
}
