import { useState } from "react";
import Head from "next/head";
import { RandomFox } from "../src/components/RandomFox";

const randomNumber = (): number => {
  let valueFinal: number = 123;

  const resultRandom: number = Math.floor(Math.random() * valueFinal);
  return resultRandom;
};

export default function Home() {
  // const [images, setImages] = useState<string[]>([]); other
  const [images, setImages] = useState<Array<string>>([
    `https://randomfox.ca/images/${randomNumber()}.jpg`,
    `https://randomfox.ca/images/${randomNumber()}.jpg`,
    `https://randomfox.ca/images/${randomNumber()}.jpg`,
    `https://randomfox.ca/images/${randomNumber()}.jpg`,
  ]);

  return (
    <>
      <Head>
        <title>React With Typescript</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-3xl font-bold underline">Hello world!</h1>
        {images.map((image, index) => (
          <div key={index} className="p-4">
            <RandomFox image={image} />
          </div>
        ))}
      </main>
    </>
  );
}
